name: Fail On PR Review

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  list-changed-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 

    - name: Print changed files
      run: | 
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        if [ -n "$CHANGED_FILES" ]; then
          echo "$CHANGED_FILES" | python print_changed_files.py
        fi
      shell: bash